### ISSUE TITLE
Sample State Design Doc Reviews

### ISSUE THREAD

**Issue by rlim92** [jas-singh-code/Fullstack_OurSpace#2]
Hey Jaspreet! Sample state looking good, some suggestions below:

### Sample State
- [ ] `likes` doesn't need its own slice of state, instead have  a `liker_ids` key-value pair that holds an array of liker ids for  a `post` or `comment`.

Everything else looks good. Make sure to get in backend and frontend route design docs!

**Comment by jas-singh-code** [comment]
Duly noted, Rich.

I've also added the frontend and backend routes to my design docs, feel
free to check it out: Design Docs Wiki
<https://github.com/jas-singh-code/Fullstack_OurSpace/wiki>

Yours truly,

Jaspreet Singh



B.A Political Science & Legal Studies

*Skadden, Arps, Slate, Meagher, & Flom LLP,* Legal Fellow
